from cifarformat import in_mem_block
from cifarformat import in_mem_block_only
from cifarformat import in_mem_sliding_window
from cifarformat import in_mem_bismarck
from cifarformat import in_mem_once_fully_shuffle
from cifarformat import in_mem_always_fully_shuffle
from cifarformat import in_mem_no_shuffle
from cifarformat import loader