from nlpformat.in_mem_sliding_window import dataset

from nlpformat.in_mem_sliding_window.dataset import InMemSlidingWindowDocDataset
from nlpformat.in_mem_sliding_window.dataset import InMemSlidingWindowSentDataset

