from nlpformat.in_mem_once_fully_shuffle import dataset
from nlpformat.in_mem_once_fully_shuffle.dataset import InMemOnceFullyShuffleDocDataset

from nlpformat.in_mem_once_fully_shuffle.dataset import InMemOnceFullyShuffleSentDataset
